### PR TITLE
MRG: BUG: use linewidth from HNNGUI to plot SimCanvas

### LINKED ISSUE #286: line width does not change
When I do the following:

Edit > Change line width

It does not affect the line width at all

### PR DESCRIPTION
**Pull request by blakecaldwell**
Fixes #286

### CODE REVIEW

**Comment by jasmainak** [comment]
I don't quite get how this fixes the problem. The before and after code looks exactly equivalent to me. What am I missing?

**Comment by blakecaldwell** [comment]
> I don't quite get how this fixes the problem. The before and after code looks exactly equivalent to me. What am I missing?

The `parent` parameter passed into `SimCanvas()` is the `HNNGUI` window.  So while `SimCanvas()` gets repeatedly reinitialized, attributes of `HNNGUI` persist for the application lifetime.

**Comment by jasmainak** [comment]
Got it, thanks!

**Comment by jasmainak** [comment]
Thanks @blakecaldwell !

**Pull request merged**
