### PR TITLE
BUG: savefigs exception

### PR DESCRIPTION
**Pull request by blakecaldwell**
Found an exception on a linux VM when save_figs was true, but save_spec was 0, and no rhythmic feeds were defined.

### CODE REVIEW

**Comment by blakecaldwell** [comment]
The exception:
Screen Shot 2021-03-28 at 6 37 02 PM

**Review by jasmainak — APPROVED** [review]
There is no CI? I seem to remember there was some continuous integration ...

**Comment by blakecaldwell** [comment]
No CI b/c of credits on Travis. I'm not sure if there's a monthly quota or if the project is already in the hole

**Comment by blakecaldwell** [comment]
Thanks for the review @jasmainak

**Pull request merged**
