### PR TITLE
record soma transmembrane currents (ina and ik for now)

### PR DESCRIPTION
**Pull request by vogdb**
Please don't merge. This PR is for a demonstration, at least for now. @samnemo please look at my questions.

- should we add transmembrane currents to `Cell.dict_currents`? If none then I would propose to store them in a single dict.
- should we put insertion of `hh2` into `Cell.__biophys_soma()`, e.g. move the common part to the parent's class? Now all cells insert it on their own. I'm using this fact now to have only single method `Cell.record_i_soma`.

### CODE REVIEW

**Comment by samnemo** [comment]
> Please don't merge. This PR is for a demonstration, at least for now. @samnemo please look at my questions.
> 
> * should we add transmembrane currents to `Cell.dict_currents`? If none then I would propose to store them in a single dict.

Yes, makes sense to put all somatic transmembrane currents into that single dictionary (Cell.dict_currents).

> * should we put insertion of `hh2` into `Cell.__biophys_soma()`, e.g. move the common part to the parent's class? Now all cells insert it on their own. I'm using this fact now to have only single method `Cell.record_i_soma`.

Yes, makes sense to put common parts into the parent class.

**Comment by vogdb** [comment]
> Yes, makes sense to put all somatic transmembrane currents into that single dictionary (Cell.dict_currents).

Made it. Now we save to `file_isoma.pkl` as the existing `file_vsoma.pkl`. Should we better save to some table format instead? It would be a table of 4 columns then: `['ik', 'ina', 'gabaa', 'gabab']`.

> Yes, makes sense to put common parts into the parent class.

Couldn't do it. Actually I've spent on it more than an hour. With current class hierarchy it would not give much profit. We can't call parent's `Cell.__biophysics()` in parent's `Cell.__init__` as it should be executed after it and also after cell's topology. So `Cell.__biophysics()` should be called from its child's `__biophysics` which doesn't give much profit as it would have only `hh2` instantiation and save only one line of code. I propose to discuss it in a call.

**Comment by blakecaldwell** [comment]
Checking on the status of this PR. @samnemo would you say that we should keep this feature in the queue?

**Comment by samnemo** [comment]
I don't think it's important for the current version of HNN, given that it will be a simple addition once we switch over to NetPyNE specification.

**Pull request closed without merging**
